### ISSUE TITLE
Come up with a market name for the project

### ISSUE THREAD

**Issue by mj0331** [proiect-colectiv-online-voting-system/PC-Nokia#8]
Required for the university paperwork, we have to come up with a catchy name that should appeal to the masses

**Comment by AndreiManea** [comment]
VoteForTheCause || JustVote || SimpleVote || SpeedVote || VoteTown || VoteToTheWorld || GeneralVote || FreshVote || VirtualVote

**Comment by mj0331** [comment]
VirtualVote it is
